### ISSUE TITLE
[Bug]: Farming Bar not including [Lightning Steel Ingot] when it is stored in the reagent bank

### ISSUE THREAD

**Issue by karpana** [nikkisaurus/FarmingBar#64]
### Interface Version

11.0.0

### AddOn Version

FarmingBar-v3.10.1.zip

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

Activated the "use Bank" option on the farming goal
moved 25 Lightning Steel Ingots from my bags into my Reagent Bank (the tracker went from 25/100 to 0/100)
moved 25 Lightning Steel Ingots from my reaget bank into my bags (the tracker went from 0/100 to 25/100)
moved 25 Lightning Steel Ingots from my bags into my Bank (the tracker stayed at 25/100)

![image](https://github.com/user-attachments/assets/a9019241-6edc-4231-8623-8000d0fef960)
![image](https://github.com/user-attachments/assets/2883c470-1296-460c-938c-8ed8c4c06353)
![image](https://github.com/user-attachments/assets/c39e5e6b-ac9a-4466-b3ac-34fc1907c021)

### Did you encounter any Lua errors related to this issue? If so, please provide them here.

No Lua errors related to this addon are present in BugSack

### Please supply any screenshots relevant to this issue.

Screenshots provided above in the Steps section

### Please supply a copy of your saved variables. You may need to save the file as a .txt file to upload here.

FarmingBarDB = {
["global"] = {
["version"] = 7,
["settings"] = {
["tooltips"] = {
["useGameTooltip"] = true,
["showDetails"] = true,
},
},
},
["profileKeys"] = {
["Carthusian - Arygos"] = "Default",
["Astronomer - Ysera"] = "Default",
["Ghostwheel - Ysera"] = "Default",
["Laadora - Ysera"] = "Default",
["Varlooch - Ysera"] = "Default",
["Silanah - Arygos"] = "Default",
["Plutocrat - Ysera"] = "Default",
["Salliistari - Stormrage"] = "Default",
["Tibal - Ysera"] = "Default",
["Karpana - Garrosh"] = "Default",
["Leandro - Ysera"] = "Default",
["Rhyu - Ysera"] = "Default",
["Emurlahn - Ysera"] = "Default",
["Physicist - Llane"] = "Default",
["Karpana - Doomhammer"] = "Default",
["Parkana - Ysera"] = "Default",
["Mandevyne - Arygos"] = "Default",
["Zardaukar - Stormrage"] = "Default",
["Parkana - Arygos"] = "Default",
["Venhold - Ysera"] = "Default",
["Carthusian - Ysera"] = "Default",
["Fuzy - Llane"] = "Default",
["Rythok - Ysera"] = "Default",
["Febryl - Ysera"] = "Default",
["Karpana - Ysera"] = "Default",
["Karpana - Aman'Thul"] = "Default",
["Aantheaoria - Illidan"] = "Default",
["Gryllen - Ysera"] = "Default",
["Vqshonon - Area 52"] = "Default",
["Bleys - Ysera"] = "Default",
["Karpana - Thorium Brotherhood"] = "Default",
},
["profiles"] = {
["Default"] = {
["bars"] = {
{
["buttonPadding"] = 0,
["point"] = {
"TOPRIGHT",
nil,
"TOPRIGHT",
0,
-332.380615234375,
},
["scale"] = 0.65,
["buttonsPerAxis"] = 14,
["buttonGrowth"] = "COL",
["skin"] = "FarmingBar_Minimal",
["hideInCombat"] = true,
["numButtons"] = 56,
["buttons"] = {
[55] = {
["onUse"] = {
["macrotext"] = "",
["type"] = "ITEM",
["itemID"] = 211515,
},
["trackers"] = {
{
["type"] = "ITEM",
["objective"] = 1,
["includeAllFactions"] = false,
["id"] = 211515,
["includeBank"] = false,
["name"] = "Splintered Spark of Awakening",
["includeGuildBank"] = {
},
["includeAlts"] = false,
["altIDs"] = {
},
},
},
["objective"] = 2,
["mute"] = false,
["condition"] = {
["func"] = "function(trackers, GetTrackerCount)\n    -- This is the structure of the tracker table:\n    --trackers = {\n    --    [1] = {\n    --        type = \"ITEM\", -- \"CURRENCY\"\n    --        id = 0000,\n    --        objective = 1,\n    --        includeAllFactions = false,\n    --        includeAlts = false,\n    --        includeBank = false,\n    --        includeGuildBank = {\n    --             [\"GuildKey\"] = true\n    --        },\n    --        altIDs = {\n    --            {\n    --                type = \"ITEM\", -- \"CURRENCY\"\n    --                name = \"\",\n    --                id = 0000,\n    --                multiplier = 1,\n    --            }\n    --        },\n    --    },\n    --}\n    \n    -- NOTE: make sure the first argument of GetTrackerCount is nil\n    -- This function is not necessary, but available if your custom function is simple and doesn't change the way each tracker is calculated.\n    --local count =  GetTrackerCount(_, trackers[1])\n    \n    return GetTrackerCount(_, trackers[1])\nend",
["type"] = "ALL",
},
["icon"] = {
["id"] = 4638425,
["type"] = "AUTO",
},
["title"] = "Splintered Spark of Awakening",
},
[54] = {
["onUse"] = {
["macrotext"] = "",
["type"] = "ITEM",
["itemID"] = 94111,
},
["trackers"] = {
{
["type"] = "ITEM",
["objective"] = 1,
["includeAllFactions"] = false,
["id"] = 94111,
["includeBank"] = true,
["name"] = "Lightning Steel Ingot",
["includeGuildBank"] = {
},
["includeAlts"] = false,
["altIDs"] = {
},
},
},
["objective"] = 100,
["mute"] = false,
["icon"] = {
["id"] = 576649,
["type"] = "AUTO",
},
["condition"] = {
["func"] = "function(trackers, GetTrackerCount)\n    -- This is the structure of the tracker table:\n    --trackers = {\n    --    [1] = {\n    --        type = \"ITEM\", -- \"CURRENCY\"\n    --        id = 0000,\n    --        objective = 1,\n    --        includeAllFactions = false,\n    --        includeAlts = false,\n    --        includeBank = false,\n    --        includeGuildBank = {\n    --             [\"GuildKey\"] = true\n    --        },\n    --        altIDs = {\n    --            {\n    --                type = \"ITEM\", -- \"CURRENCY\"\n    --                name = \"\",\n    --                id = 0000,\n    --                multiplier = 1,\n    --            }\n    --        },\n    --    },\n    --}\n    \n    -- NOTE: make sure the first argument of GetTrackerCount is nil\n    -- This function is not necessary, but available if your custom function is simple and doesn't change the way each tracker is calculated.\n    --local count =  GetTrackerCount(_, trackers[1])\n    \n    return GetTrackerCount(_, trackers[1])\nend",
["type"] = "ALL",
},
["title"] = "Lightning Steel Ingot",
},
[56] = {
["onUse"] = {
["macrotext"] = "",
["type"] = "ITEM",
["itemID"] = 211516,
},
["trackers"] = {
{
["type"] = "ITEM",
["objective"] = 1,
["includeAllFactions"] = false,
["id"] = 211516,
["includeBank"] = false,
["name"] = "Spark of Awakening",
["includeGuildBank"] = {
},
["includeAlts"] = false,
["altIDs"] = {
},
},
},
["objective"] = 1,
["mute"] = false,
["icon"] = {
["id"] = 4693222,
["type"] = "AUTO",
},
["condition"] = {
["func"] = "function(trackers, GetTrackerCount)\n    -- This is the structure of the tracker table:\n    --trackers = {\n    --    [1] = {\n    --        type = \"ITEM\", -- \"CURRENCY\"\n    --        id = 0000,\n    --        objective = 1,\n    --        includeAllFactions = false,\n    --        includeAlts = false,\n    --        includeBank = false,\n    --        includeGuildBank = {\n    --             [\"GuildKey\"] = true\n    --        },\n    --        altIDs = {\n    --            {\n    --                type = \"ITEM\", -- \"CURRENCY\"\n    --                name = \"\",\n    --                id = 0000,\n    --                multiplier = 1,\n    --            }\n    --        },\n    --    },\n    --}\n    \n    -- NOTE: make sure the first argument of GetTrackerCount is nil\n    -- This function is not necessary, but available if your custom function is simple and doesn't change the way each tracker is calculated.\n    --local count =  GetTrackerCount(_, trackers[1])\n    \n    return GetTrackerCount(_, trackers[1])\nend",
["type"] = "ALL",
},
["title"] = "Spark of Awakening",
},
},
["movable"] = false,
["fontstrings"] = {
["Count"] = {
["x"] = 0,
["y"] = 0,
},
["Objective"] = {
["x"] = 0,
["y"] = 0,
},
},
},
},
["style"] = {
["buttons"] = {
["padding"] = 0,
},
},
},
},
}
FarmingBarDevDB = nil

**Comment by nikkisaurus** [comment]
I will push a fix for this some time this week. I've made the adjustment but had to fix another error, too, and I need to test it for classic as well before I release.

**Comment by nikkisaurus** [comment]
Should be fixed in [v3.11.0](https://github.com/nikkisaurus/FarmingBar/releases/tag/v3.11.0). Feel free to reopen if there are further issues.

**Comment by karpana** [comment]
Not sure how to reopen the incident @nikkisaurus 
but I'm still having the same issue with reagent bank not working....

here's a screencap of the item details
![image](https://github.com/user-attachments/assets/c9689838-f1c0-4b93-b99b-958841c60c2e)

and here's a screencap of the tracker configuration
![image](https://github.com/user-attachments/assets/0dddddbf-2d50-45b5-8947-9306a6b78c4e)


I don't know what I'm doing wrong.

**Comment by nikkisaurus** [comment]
There was a missed GetItemCount call for when using DataStore specifically. Should be fixed in [v2.11.1](https://github.com/nikkisaurus/FarmingBar/releases/tag/v3.11.1).
